version: 2.0

jobs:
  build:
    docker:
      - image: cimg/base:2023.08 
    steps:
      - checkout
      - run:
          name: Add Bazel Apt Repository 
          command: |
            sudo apt install curl gnupg -y &&
            curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg &&
            sudo mv bazel.gpg /etc/apt/trusted.gpg.d/ &&
            echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
      - run:
          name: Install Bazel
          command: sudo apt update && sudo apt install -y bazel
      - run: 
          name: Build Packages
          command: |
            bazel build //... &&
            bazel run //:gazelle-update-repos &&
            bazel run //:gazelle




  deploy:
    docker:
    - image: alpine:3.14
    steps:
      - run:
          name: Setup joe
          command: |
            echo "joe" 
      - run:
          command: |
            echo "hello"

workflows:
  version: 2
  BazelCircleCIWorkshopPipeline:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - mainline 