version: 2.0

jobs:
  build:
    docker:
      - image: alpine:3.14 
    steps:
      - run:
          name: Run tests
          command: |
            echo "hello"

  deploy:
    steps:
      - run:
          name: Setup joe
          command: |
            echo "joe" 
      - run:
          command: |
            echo "hello"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build